"""alter content to text in posts

Revision ID: d05ae707faa3
Revises: 
Create Date: 2026-09-11 17:46:00.589521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd05ae707faa3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentation_languages',
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'abbr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_index(op.f('ix_documentation_languages_abbr'),
                    'documentation_languages', ['abbr'], unique=False)
    op.create_table('registration_users',
                    sa.Column(
                        'username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'firstname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column(
                        'lastname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('hashed_password',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('documentation_categories',
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('lft', sa.Integer(), nullable=False),
                    sa.Column('rgt', sa.Integer(), nullable=False),
                    sa.Column('parent_id', sa.Integer(), nullable=True),
                    sa.Column('language_id', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['language_id'], ['documentation_languages.id'], ),
                    sa.ForeignKeyConstraint(
                        ['parent_id'], ['documentation_categories.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('documentation_posts',
                    sa.Column(
                        'title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('content', sa.TEXT(), nullable=False),
                    sa.Column('online', sa.Boolean(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('language_id', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['documentation_categories.id'], ),
                    sa.ForeignKeyConstraint(
                        ['language_id'], ['documentation_languages.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('slug'),
                    sa.UniqueConstraint('title')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentation_posts')
    op.drop_table('documentation_categories')
    op.drop_table('registration_users')
    op.drop_index(op.f('ix_documentation_languages_abbr'),
                  table_name='documentation_languages')
    op.drop_table('documentation_languages')
    # ### end Alembic commands ###
